# These are supported funding model platforms

github: GorillaPool
custom: https://getbux.io/?utm_source=github&utm_medium=sponsor-link&utm_campaign=bux-website&utm_term=bux-website&utm_content=bux-website
